enum Icon {
  // Brands
  Canary = "canary",
  Chancery = "chancery",
  Cie = "cie",
  Nasdaq = "nasdaq",
  Maily = "maily",
  Neetcode = "neetcode",
  Slik = "slik",
  NzGovt = "nzgovt",
  Panopto = "panopto",
  Piston = "piston",
  Qantas = "qantas",
  Redbull = "redbull",
  UoA = "uoa",
  USYD = "usyd",
  Yourcar = "yourcar",
  YouTube = "youtube",
  // Tech
  Angular = "angular",
  AWS = "aws",
  CSharp = "csharp",
  Docker = "docker",
  DotNet = "dotnet",
  Go = "go",
  GraphQL = "graphql",
  Jenkins = "jenkins",
  MongoDB = "mongodb",
  PostgreSQL = "postgresql",
  Python = "python",
  React = "react",
  Svelte = "svelte",
  Swift = "swift",
  ThreeJS = "threejs",
  TypeScript = "typescript",
  Vue = "vue",
  Empty = "",
}

export default Icon;
