export const BLOCK_PADDING = 10;
export const BLOCK_PADDING_DESKTOP = 25;
export const BLOCK_WIDTH = 500;
export const BLOCK_WIDTH_DESKTOP = 580;
export const IMAGE_DEFAULT_HEIGHT = 50;
export const MEDIA_TOP_OFFSET = 220;
export const MEDIA_TOP_OFFSET_DESKTOP = 240;
export const MEDIA_MARGIN_LEFT =
  (BLOCK_WIDTH - 2 * BLOCK_PADDING_DESKTOP - 360) / 2;
export const MEDIA_MARGIN_LEFT_DESKTOP =
  (BLOCK_WIDTH_DESKTOP - 2 * BLOCK_PADDING_DESKTOP - 385) / 2;
